### ISSUE TITLE
[Proposal] Create a "Design" and "Development" label in GitHub

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#1019]
When looking at the list of issues in the [Waffle board](https://waffle.io/vanilla-framework/vanilla-framework) it's hard to distinguish straight away which ones are design and which ones are development related.

Could we create labels to make this distinction easier to see?

**Comment by anthonydillon** [comment]
That is one way. But something that would have to be manually kept up. I
wonder if filtering the waffle board to only show design repository's would
be more true and less error prone.

**Comment by yaili** [comment]
Maybe, but we'd also need to manually make sure there's no tasks for designers in the other repos.

**Comment by barrymcgee** [comment]
Wondering how difficult it would be to build a little chrome extension to add a little coloured top border on design/developer tickets based on repo?

**Comment by barrymcgee** [comment]
Decided to see if I could hack together a little Chrome Extension to scratch this itch tonight - got it working so that all issues from non-design related repos have a 3px orange top border:

<img width="995" alt="screen shot 2017-04-12 at 23 26 47" src="https://cloud.githubusercontent.com/assets/505570/24982088/8bbefa62-1fd7-11e7-9e43-2b40ac0d9aa5.png">

To install it yourself:

1. Download [waffle-strips.zip](https://github.com/vanilla-framework/vanilla-framework/files/918019/waffle-strips.zip)
2. Unzip the folder
2. Open Chrome
3. Go to [chrome://extensions/](chrome://extensions/)
4. Drag and drop the unzipped folder named 'waffle-strips' into the Chrome extensions window
5. Go to https://waffle.io/vanilla-framework/vanilla-framework
6. Profit?

**Comment by yaili** [comment]
Cool!

Is red developer and design has no colour?

**Comment by barrymcgee** [comment]
Developer is current Ubuntu orange and design has no colour..

**Comment by anthonydillon** [comment]
We now have a project for this extension. Thanks @barrymcgee.
https://github.com/canonical-webteam/waffle-strips/
