### ISSUE TITLE
External link icon seems stretched

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-framework#1058]
# 1. Bug template

## Process

1. Go to https://docs.vanillaframework.io/en/patterns/links and look at the external icon links

## Expected result

The box part of the icon should be squared.

## Current result

I'm not 100% sure this is true, but to my naked eye the icon looks slightly distorted, stretched horizontally by maybe 1px. 

I can't debug properly because the image file is referenced in a way that it's not easy to, but changing the height to 14px makes it look better, but cropped, which is also not great.

Could someone have a look at this?

**Comment by barrymcgee** [comment]
I think this issue is no longer valid. Since this issue was raised, we have changed how we display this icon, which probably fixed it. When inspecting the icon at normal size, or fully zoomed, it is perfectly and proportionately square.

![Screen Shot 2017-08-22 at 15.28.37.png](https://images.zenhubusercontent.com/593146f551aa2c3057803b7c/5de41bfc-ecff-4ce5-8a9b-2710e200cd93)

![Screen Shot 2017-08-22 at 15.28.16.png](https://images.zenhubusercontent.com/593146f551aa2c3057803b7c/a4e3c017-5cc1-4a73-bb62-07346bd945e0)

**Comment by barrymcgee** [comment]
@kwm14 You can view the icon yourself here: https://vanilla-framework.github.io/vanilla-framework/examples/patterns/links/links-external/

Can you review comment above and close this issue if you agree?

**Comment by kwm14** [comment]
Stretched icon is fixed. Performed same test as Barry normal size and zoomed in to make sure proportion scales.

Closing issue as fix was made in previous [release](https://github.com/vanilla-framework/vanilla-framework/commit/05271d2925a06d3afef2ca53d591f0cd6aa39c86#diff-d7752a4a8746b85e104fce6adba241ef).
