### ISSUE TITLE
Build layout modification

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1216]
Vanilla docs theme has extra styling which modifies the layout. This need to be made an option in Vanilla.

**Comment by barrymcgee** [comment]
I believe this is now an extra section of Vanilla entirely and should be labelled as such -

Settings / Base / Pattern / **Layout** / Utilities

@anthonydillon Thoughts before moving forward?

**Comment by anthonydillon** [comment]
I thought that at first. But, I would like that all of the patterns would
work/scale to the layout they are placed in.

For example, instead of modifying the header navigation to align vertically
down the left hand side (docs theme). The framing markup/grid settings
should change the layout of the page. Then simple place the vertical
navigation pattern within the layout.

Previously we have tried to keep the mark up the same between layouts but I
don't think we should any more. The framing of the site should different
and therefore more flexible to allow most layouts.

This can lead us to adopting grid CSS sooner.

Does any of this make sense?

**Comment by barrymcgee** [comment]
So, how would this work in practice - adding a class to the body of `vf-l-docs` or similar and namespace all specific styling under that?

**Comment by anthonydillon** [comment]
No not at all. All patterns should be useful with other patterns.
Therefore, they all have the same importance.

The layout should be dictated by the markup used. For example, the
side/vertical navigation could be placed inside a `col-4` on the left hand
side which means it takes up that amount of space.

All patterns should scale to the parent container. This means to change the
layout you simple construct the page frame differently.

This means that patterns should be either considered as modifications or
entirely new patterns when migrating patterns from other themes.

**Comment by barrymcgee** [comment]
I agree, and that's what we have currently - all patterns fill the space allowed their parent. 

To that end, you can roughly achieve a docs layout by changing the `$grid-max-width` variable to 100%

I've quickly mocked this up in a [feature branch](https://github.com/barrymcgee/vanilla-framework/tree/docs-layout) - run locally and view the ''Docs layout" example under "Templates"

What we don't currently have is any styles to define the right border on the nav sidebar as it's only needed in this particular context - which is why I think if we're going to go down this route, we'll need to somehow namespace it.

**Comment by anthonydillon** [comment]
I think the docs template is good for a first pass. Can you create a PR with is please. Shame there isnt a way to set the `$grid-max-width` in the template.

**Comment by anthonydillon** [comment]
In fact, the jump is there on all of our sites. I think we can consider this closed as its a font loading issue.
