### ISSUE TITLE
prefix patterns that require them

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-framework#1351]
## Process

use .p-link--external on a site without and autoprefixer and things like .p-link--external and select don't work correctly.

## Expected result

Vanilla should work 'out of the box' for the latest browsers

## Current result

The patterns don't work in latest Chrome for example (see screenshot)

## Screenshot

![image](https://user-images.githubusercontent.com/441217/30581838-77065c5e-9d19-11e7-899e-a783572c50de.png)

**Comment by barrymcgee** [comment]
There is a note on the [links page in the docs](https://docs.vanillaframework.io/en/patterns/links) about the need to use Autoprefixer.

The reason for this is that we only project the raw Sass, and each site tool chain is unique.

With this particular issue however, we've identified that support for CSS masks is very sketchy indeed and should ever have been used in the first place due to zero support in IE so a [critical bug](https://github.com/vanilla-framework/vanilla-framework/issues/1346) is currently being worked on to address this.
