### ISSUE TITLE
Investigate Vanilla base size

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1640]

**Comment by Caleb-Ellis** [comment]
Issue blocked until Vanilla 1.7.0 beta (with new Vanilla spacing) has been QA'd and merged, because it affects pretty much all the scss files this issue would deal with, causing significant conflicts.

**Comment by Caleb-Ellis** [comment]
# Findings

- Below is a spreadsheet of all base components:

![screenshot_6](https://user-images.githubusercontent.com/25733845/39474805-9ece3ef2-4d4d-11e8-8947-aa7e2428f3ef.png)

## Actions

I think the following issues need to be addressed:
- The Forms component is far and away the biggest component of the base Vanilla files. This is due to the incredibly high number of permutations of an input element - whether it's the first or not in a form, if it sits in a table, after a paragraph, consecutive after a paragraph, etc. I think the way placeholders are used can be improved to be a bit more targeted, for example we could have a generic style for `input` elements, and then have placeholders that override styling for special cases like checkboxes and radio buttons. That way we don't have a list of 20 different input element selectors for every situation. This will require a lot of experimentation, however, as we don't want to inadvertently break an `input[type='month']` or something similar
- Utilities are quite large because it includes 16 different utilities, each of which is ~300-500b. Individually I don't think performance can be improved, but we could consider removing ones that aren't used.
- Typography is also quite large, for similar reasons to the base Form pattern (lots of permutations), although not nearly as big. Its use of placeholders is already quite targeted, and carefully considered, so I believe there are limited gains to be made here.
- The rest of the components are too small to warrant further investigation
- There are a couple of small issues with placeholders being used between base components, so I suggest we bring the common ones into base_placeholders (not that anyone would be splitting out base components, but still...). There is also an issue with `%p-button--positive` being used in base forms, which should be fixed so base can be imported alone.
