### ISSUE TITLE
Investigate Vanilla patterns sizes

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1641]

**Comment by Caleb-Ellis** [comment]
Issue blocked until Vanilla 1.7.0 beta (with new Vanilla spacing) has been QA'd and merged, because it affects pretty much all the scss files this issue would deal with, causing significant conflicts.

**Comment by Caleb-Ellis** [comment]
# Findings

- Below is a spreadsheet of all components over 2000b in size:

![screenshot_4](https://user-images.githubusercontent.com/25733845/39470464-d3581c50-4d35-11e8-9348-ca37ac479466.png)

## Actions

I think the following issues need to be addressed:
- There are still some encapsulation issues, mostly to do with `.p-card--highlighted`, and a couple others. My suggestion is to bring these commonly used styles into `base_placeholders` which can then be extended where needed.
- The Icons are the biggest pattern by a large margin, which is expected. Notably, the social icons (of which there are 8, each with a different colour on hover) are twice as large as the normal icons (of which there are 22, each with a different colour on dark backgrounds). I think we should consider whether we want these social icons in Vanilla, or if we should just provide the markup to have them as inline SVGs in which case the user would have to style the on-hover colour change themselves.
- The Links pattern is unusually large, given how relatively simple it is. It is due to the way the external link icon is handled to be able to adopt the colour of the text AND be able to work on older browsers. I think we should look at using placeholders where possible, and reconsider how to approach cross-browser support.
- The Buttons pattern is also quite large, due to the number of permutations of a button that has: animation, hover/active/disabled state, text/background/border colour. I think we should look at how placeholders are currently being used, as there might be a bit of redundancy - e.g. having the `p & + &` selector inside the `%vf-button-base` placeholder means that the built css has a selector for every combination of a paragraph followed by two buttons (`p .p-button--base + .p-button--base`, `p .p-button--base + .p-button--neutral`, etc) whereas the same result might be achievable simply with `p button + button`.
- There seems to be a lot of redundancy in the Sidebar navigation pattern. Separating out common elements between header and sidebar nav into placeholders should help with the filesize. Alternatively, we should reconsider whether we want to keep the Sidebar navigation pattern, as it seems to be able to be built out of a combination of a logo, a select, an accordion, an hr, and links. Where do we use it currently?
- The grid is relatively large, but it also achieves a lot and changes to it could be catastrophic. I suggest we leave it for now as the risk/reward ratio is a bit naff.
- The media object pattern has a few icons that aren't included in the icons pattern? This should be discussed.
- The rest of the large-ish components use icons, or build on top of `.p-card--highlighted`. As mentioned before it might help to use placeholders effectively.

**Comment by anthonydillon** [comment]
Really good analysis. Great kick off to a performance epic.
