### ISSUE TITLE
Header has lost some spacing

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#1658]
During the conversion of the cloud-init.io site. I noticed that the header has changed. 

It seems that the:
- logo size is set to `24px` but was `32px` before
- there was margin around the entire logo but it has no margin bottom now

Before:
![screenshot-2018-4-2 cloud-init - the standard for customising cloud instances](https://user-images.githubusercontent.com/1413534/38192117-6233132e-3663-11e8-8ccb-ef85b6bb6233.png)

After:
![screenshot-2018-4-2 cloud-init - the standard for customising cloud instances 1](https://user-images.githubusercontent.com/1413534/38192125-6b847e5e-3663-11e8-95aa-d74c9483f3ea.png)

**Comment by Caleb-Ellis** [comment]
The issue seems to be related to the following:
- Navigation height is now dictated by the content
- The only content in the cloud-init nav is the logo
- Logos are now given an explicit height of 24px

There seems to be a disconnect between whether we do or don't want to set heights in the new vanilla nav. Do we want the logo to set its own height? Does that play well with the spacing variables? If we want the logo height to be explicit, should we make the nav height explicit too to give it some consistency? Calling @kwm14, @lyubomir-popov and @anthonydillon on thoughts about this.

**Comment by anthonydillon** [comment]
Consistency of the great height is paramount. Ideally all content within the header should be the same height. Resulting in the header begging the same height without strange alignment. Once we have the logo, navigation and search all the same height it can't hurt to hard at the height as its so important.

If the headers are different heights across the sites it is very noticeable and damaging to the overall experience.

**Comment by lyubomir-popov** [comment]
@anthonydillon @Caleb-Ellis @kwm14 Sorry I half-implemented this, and it causes confusion. 
The headers should be same height of course, and my intention was for the logo to be up to (max-height) 32px. If less, it should be vertically centered in the available 32px.

This gives a little flexibility with the logo size (range 24-32px), which can be quite useful (as the line-height of the menu items is 24px) and would ensure it never goes above that and change the height of the nav.
