### ISSUE TITLE
Muted heading has margin-bottom by default

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1665]
## insights.ubuntu.com upgrade to v1.7.0-alpha-1
Reviewing the beta test branch I noticed that `p-muted-heading` is applying margin-bottom: 15px; which is causing unnecessary padding to elements it's contained within.

Link to issue: http://insights.ubuntu.com-pr-290.run.demo.haus/

## Expected result
![screen shot 2018-04-03 at 10 33 47](https://user-images.githubusercontent.com/17748020/38241585-84ab409e-372a-11e8-84b6-504d8ee8d63e.png)

## Current result
![screen shot 2018-04-03 at 10 32 42](https://user-images.githubusercontent.com/17748020/38241566-78d2b3ec-372a-11e8-8332-434adfce2f18.png)

**Comment by anthonydillon** [comment]
This should be a card level override as I believe we want the margin-bottom on a stand alone `p-muted-heading`.

**Comment by kwm14** [comment]
Agreed to add this card-component to Vanilla.

**Comment by kwm14** [comment]
I've added to Vanilla backlog for a new component/modifier of the current card component. 

+1 @anthonydillon comment that for now it will be a card level override.

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis could you leave this issue open please? I'd like to add this to the vanilla card component with slight adjustments - so that the spacing above/underneath matches other places the muted heading is "sandwiched" between borders, like table headers. 
As it is now, the space above/below is a bit too wide for such a small font-size, if you compare with the expected result above - 
![image](https://user-images.githubusercontent.com/2741678/38632204-ec69d80a-3db3-11e8-9a28-98c6166788d8.png)

**Comment by Caleb-Ellis** [comment]
@lyubomir-popov No worries. Closing the original PR for now.

**Comment by lyubomir-popov** [comment]
#1713 addresses part of this by adding a muted header card to vanilla. This pattern is currently used in only two places, so I've taken the liberty of altering the makrup a bit.

**Comment by lyubomir-popov** [comment]
@Caleb-Ellis Why are the image and heading with different Google Analytics tracking code? 
Shouldn't a card acting as a link to somewhere be clickable as a whole, meaning all content under .p-card wrapped in one <a>?
