### ISSUE TITLE
Cards missing left margin when used in p-list 

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1677]
## ubuntu.com v1.7.0-alpha-1
Reviewing the beta test branch. Cards missing left margin when used in p-list so they're all touching.

Link to issue: http://www.ubuntu.com-pr-2859.run.demo.haus/cloud

## Current result
![screen shot 2018-04-04 at 15 32 05](https://user-images.githubusercontent.com/17748020/38314365-e486c116-381d-11e8-9f43-ae72003c17a9.png)

## Expected result
![screen shot 2018-04-04 at 15 35 39](https://user-images.githubusercontent.com/17748020/38314378-ee6f0a3a-381d-11e8-83de-42d953667a48.png)

**Comment by kwm14** [comment]
## Same issue but has 'flex' applied
This example can be found on /cloud/juju.

![screen shot 2018-04-04 at 15 41 21](https://user-images.githubusercontent.com/17748020/38314736-d87cebba-381e-11e8-9cbf-8ef10598e4b6.png)

**Comment by Caleb-Ellis** [comment]
@kwm14 @anthonydillon @lyubomir-popov 

This is an issue with the content alignment utilities, which I had updated to work with text elements that had a max-width applied. Basically they're overriding the margins set by `.col-x` classes. I think the options are:
- Remove margins being set on the `u-align` classes and have a separate utility for removing `max-width` (e.g. `u-no-max-width`).
- Remove margins being set on the regular `u-align` classes and have a separate `u-align` class that centers text elements (e.g. `u-align--center-text`)
- Rewrite markup so that `u-align--center` is never applied on a div that also has a `col-x`, but rather on a div inside that (e.g. `<div class="col-2"><div class="u-align--center">`)
