### ISSUE TITLE
Code snippet icon not aligned inside input field

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1681]
## ubuntu.com v1.7.0-alpha-1
Reviewing the beta test branch. Code snippet copy icon not aligned to top of input field.

Issue can be found here: http://www.ubuntu.com-pr-2859.run.demo.haus/support/esm

### Current result
![screen shot 2018-04-04 at 17 14 16](https://user-images.githubusercontent.com/17748020/38320176-c4ead942-382b-11e8-8d91-aa54942b51f9.png)

**Comment by lyubomir-popov** [comment]
This is due to markup not matching the vanilla example – .p-code-snippet should be on a div, not a p

Example markup:
![image](https://user-images.githubusercontent.com/2741678/38554414-71f1406c-3cba-11e8-9968-3041535071cf.png)

Current markup: 
![image](https://user-images.githubusercontent.com/2741678/38554478-abbdc220-3cba-11e8-8af2-ffbea4a63b3a.png)

Corrected markup:
<img width="741" alt="screen shot 2018-04-10 at 12 24 02" src="https://user-images.githubusercontent.com/2741678/38554340-264de322-3cba-11e8-96f4-87e61eb06eb2.png">

**Comment by anthonydillon** [comment]
The pattern should override the margins. Three pattern needs to be
flexibility enough to change elements and be held together by the class
names.

**Comment by lyubomir-popov** [comment]
@anthonydillon Noted, I'll add the overrides.

**Comment by lyubomir-popov** [comment]
PR here - https://github.com/vanilla-framework/vanilla-framework/pull/1701

**Comment by Caleb-Ellis** [comment]
Closed as part of #1701
