### ISSUE TITLE
Heading icon title not aligned correctly

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1731]
## v1.7.0-beta-1 review on cn.ubuntu.com

Heading icon title out of alignment, not sure if this is component fix or a CSS fix on cn.ubuntu.com.
- Issue can be found here: http://cn.ubuntu.com-pr-205.run.demo.haus/

## Current result
![screen shot 2018-04-16 at 11 49 52](https://user-images.githubusercontent.com/17748020/38805033-4e80b4b2-416c-11e8-8970-29c6c0f7067e.png)

**Comment by lyubomir-popov** [comment]
@kwm14 @Caleb-Ellis this is a tricky one. 

The icon is next to a heading, but that heading can be any of . the h1-h6 + muted, as in this case.
The problem there is, headings have a different height + margin. Not knowing what the heading is, it is impossible to make the icon line up nicely.  

I think the most sensible thing would be to enforce a heading size, e.g. h4. This would mean the tiny grey chinese text would become a regular h4. THen sizing the icon to look good next to a predictable heading is a straightforward thing.

What do you think @kwm14 ?

**Comment by lyubomir-popov** [comment]
For comparison, the same pattern is used in these two places:

<img width="1680" alt="screen shot 2018-04-18 at 17 49 50" src="https://user-images.githubusercontent.com/2741678/38946334-0ae3e550-4331-11e8-8b84-29ba3265b17f.png">
<img width="677" alt="screen shot 2018-04-18 at 17 53 03" src="https://user-images.githubusercontent.com/2741678/38946448-6208bdb0-4331-11e8-901c-9a1d7405aea2.png">

**Comment by lyubomir-popov** [comment]
A bit of context to what I did: 
Arbitrary headings can sit next to the icon in this pattern. To get the icon to lign up vertically with the heading, we need white space underneath it too. So I've applied 1rem padding. 1 rem is the smallest amount of padding we have (on muted headings).  All headings have a margin-bottom in the range .95 to 2.4 (the odd numbers are due to compensation for padding top nudges to align things to the closesrt baseline).

This allows things to almost look ok - with two caveats:
Images will be displayed at their native resolution up to the max-width/max-height. o a tiny icon would not get scaled, as is visible in the first example below.

With larger headings, the icon will sit slightly below its optimal position. This is exacerbated if the line wraps.

Unless @Caleb-Ellis has a better idea, I suggest we go with this for now and open a low-priority card to redesign the pattern to be more controllable (like putting the icon inside the heading, which would allow us to target it precisely in every case).
 
<img width="1024" alt="screen shot 2018-04-19 at 14 35 52" src="https://user-images.githubusercontent.com/2741678/38994987-b7ad2d60-43df-11e8-8ce3-1d1f35b34f2e.png">
