### ISSUE TITLE
Notification pattern - box-shadow should be optional

### ISSUE THREAD

**Issue by lyubomir-popov** [vanilla-framework/vanilla-framework#1754]
# 2. Pattern proposal/amendment

We've come across a few cases in snapcraft and maas where card styling (box-shadow + padding) is adding more prominence than needed for some notifications.

I suggest expanding the concept of a notification to include any combination of:
• icon
• text
• dismiss / close link / icon / button
• colored bar
• card styling (box-shadow + padding)

## Is this a proposal or an amendment?
- Amendment

If amendment, what is the name of the pattern to be amended?
`p-notification`

## Visual
(case where card styling is not useful:)
Provide a screenshot or link to prototype of your pattern proposal.
<img width="1323" alt="screen shot 2018-04-20 at 17 18 36" src="https://user-images.githubusercontent.com/2741678/39062532-ba46a48a-44bf-11e8-8fbc-892cdb13ca8b.png">

**Comment by kwm14** [comment]
## Agreed in WG
- we need decide the difference between a pop-up notification and an error notification inside a row 
- @matthewpaulthomas we need your UX expertise 👍

**Comment by matthewpaulthomas** [comment]
In 2009, the Ubuntu design team’s first major project was a new notification system. We found that many apps were [misusing notifications](https://wiki.ubuntu.com/NotificationDesignGuidelines), I guess because they looked sophisticated or exciting or both. Vanilla notifications are very different, but we may be prone to the same problem here.

To me, the element shown in this screenshot doesn’t look like it should be a notification. Maybe I’m misunderstanding, but it looks like it’s just text explaining why something is disabled. Is that right? That wouldn’t be an error, in which case it shouldn’t even have an error icon. The text can instead be a caption below the control, or (if possible) a brief bracketed phrase at the end of the disabled label. For example, the label might be “18.04 (used for commissioning)”, with no further elements required.

Are there any other examples?

**Comment by kwm14** [comment]
Agreed with @lyubomir-popov @spencerbygraves in our Cloud application audit that in MAAs's use case this is not an notification.

Speaking with @Caleb-Ellis @anthonydillon we can already achieve this in Vanilla:
` <p><i class="p-icon--error"></i> Hello</p>`
