### ISSUE TITLE
Rewrite confusing copy on the Typography docs page

### ISSUE THREAD

**Issue by Greggless** [vanilla-framework/vanilla-framework#1832]
## Process

https://docs.vanillaframework.io/en/base/typography

## Expected result

Headings to range from 1-->6, decreasing in height

## Current result

Headings range from 6-->1, decreasing in height
## Screenshot

https://docs.vanillaframework.io/en/base/typography

**Comment by Caleb-Ellis** [comment]
@Greggless Yeah, it's the most confusingly written section of all time. Basically it's saying that you can overwrite normal `<h1>`, `<h2>` etc HTML with `.p-heading--xxx` CSS and it'll take on a different look. So in that example, the first heading is `<h6 class="p-heading--one">` - technically it's a heading 6 but it looks like a heading 1.

I'll rename this issue and close #1833 as the issue is with the way it's written.

**Comment by Greggless** [comment]
After re-reading, I now (kind of) understand the section!
