### ISSUE TITLE
Update stepped-list component

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#1889]
## Process

Stepped-list update to allow for different text sizes, the number should scale along with it.

1. Original design issue can be seen [here](https://github.com/ubuntudesign/vanilla-design/issues/276)
2. Allow for `h3` and `h4` heading sizes
3. Number scales to same heading sizes 

## Expected result
![updated-stepped-list-001](https://user-images.githubusercontent.com/17748020/41711174-66266592-753f-11e8-95b1-0c047efb1f84.png)

## Current result
![current-stepped-list](https://user-images.githubusercontent.com/17748020/41669794-8cf26db4-74aa-11e8-8606-bfe3b0c558b9.png)

**Comment by deadlight** [comment]
The current method of setting the font size for the heading and the bullet is hard-coded to use a specific size and is linked to the bullet size and the vertical spacing. All of this is based on "heading 3" sizing at the moment.

The problem is that it is set in `%li-numbered`, which is, itself, reused for the normal and detailed stepped lists.

I think that this pattern is due a full rewrite - it seems over-engineered for its relatively simple functionality and adding another layer of hack onto it is only going to make the refactoring more difficult.
