### ISSUE TITLE
Update form states

### ISSUE THREAD

**Issue by spencerbygraves** [vanilla-framework/vanilla-framework#1933]
## Form

Update the existing styling to help with UI contrast, making form elements distinct from dividing lines etc. Also we don't currently have a hover state.

#### Updates ####

- Update border colour (#999999)

#### Additions ####

- Add a hover state (#666666)
- Add a focused state (#666666)

## Visual

![image](https://user-images.githubusercontent.com/9105999/42999813-14553380-8c17-11e8-93ea-24f33aff2e06.png)

**Comment by matthewpaulthomas** [comment]
Is there a rationale for form control hover states? I don’t see one in the notes from the design workshop.

I understand having a hover state for links in navigation menus, for example, or for a row of icon-only buttons, where the clutter from showing the affordance all the time would be worse than the distraction from invoking hover effects accidentally as you pass over them. But here, a #999999 border for an unhovered text field is hardly less cluttered than a #666666 border.

> Add a hover state (#666666)
> Add a focused state (#666666)

This could cause text to be typed into the wrong field. macOS hides the pointer whenever you start typing, so that it doesn’t obscure the typed text. So if the hover and focused states were the same colour, half the time you wouldn’t be able to tell whether a field was darker because it was focused, or darker because a hidden pointer was over it.

**Comment by spencerbygraves** [comment]
Thanks @matthewpaulthomas, I hadn't considered the cursor change when hovering over a field. And if it could cause confusion with the focused state, I'm happy to not add a hover.
