### ISSUE TITLE
Pattern: Docs p-sidenav

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#1992]
Similar to https://github.com/vanilla-framework/vanilla-framework/issues/1991, both docs.vanillaframework.io and discourse-docs.staging.snapcraft.io use a sidenav that sits inside the sidebar. The difference is that in the case of discourse-docs, we don't get to control the markup and it can't have classes added to it.

I've created [a pattern for discourse-docs for this sidenav](https://github.com/nottrobin/discourse-docs.snapcraft.io/blob/word-break/static/sass/_patterns_sidenav.scss), which we might want to consider including in Vanilla (although probably not in this exact form).

**Comment by kwm14** [comment]
## Agreed in WG
- This work is part of our 2.0 release
- New side-bar on it's way
- @nottrobin also can you update your link as it's 404 so we know what your referencing

**Comment by deadlight** [comment]
@nottrobin it has been decided that the sidenav component isn't needed because it is simply a frame for other elements to sit in and can be constructed from existing components on the grid.

If this means that you'll have problems with your specific sites then feel free to speak to me about possible solutions.
