### ISSUE TITLE
Validation on select inputs

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#2044]
When adding validation to a select input the icon appears over the arrow. We should probably position it so we can see both.

![screenshot_2018-11-02 fast-shrew sample maas-dev2 maas](https://user-images.githubusercontent.com/1413534/47944232-250f1f00-def2-11e8-9e78-af8ac5eedc03.png)

**Comment by deadlight** [comment]
Have been thinking about/experimenting with this:
 - <select> can't have an ::after so that isn't an option
 - Multiple background images would work but requires special cases for <select> inputs, a  dependency between the base_forms and patterns_validation, and would duplicate the images in the CSS multiple times, bloating the file
 - Moving the icons to the wrapper is risky and would make the component too brittle to other changes

There's, no clear winner in my mind.

Suggestions appreciated!
