### ISSUE TITLE
Reduce complexity 

### ISSUE THREAD

**Issue by kwm14** [vanilla-framework/vanilla-framework#2099]

**Comment by lyubomir-popov** [comment]
The title of this may be a bit misleading - or maybe I picked the wrong issue? Essentially the pr makes spacing much more harmonious, which does result in some simplification, but as a side effect rather than as a goal.

The linked pr refactors the huge _typography.scss file though. Functionality has been moved to:


```@import 'settings'; ``` – typographic settings
```@import 'base_font-declarations'; ``` – the fontface declarations
```@import 'base_measure'; ``` – max-widths 
```@import 'base_heading-definitions'; ``` – actual heading rules
```@import 'base_heading-mixins';``` – heading mixins

**Comment by kwm14** [comment]
@lyubomir-popov is this issue no longer valid?

**Comment by lyubomir-popov** [comment]
I wasn't sure what this is about, so I moved the pr to the other issue.

**Comment by kwm14** [comment]
Ok. So is this issue no longer relevant? @deadlight @lyubomir-popov

**Comment by lyubomir-popov** [comment]
Unless @deadlight knows what it was about I'd close it.
