### ISSUE TITLE
Compilation error in > 1.8.0

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#2121]
**Describe the bug**
When trying to consume Vanilla Framework on a separate site, I'm hit with a Sass compilation error. 

This error is only present in `1.8.0` and `1.8.1`

**To Reproduce**
1. Clone this isolated test case: https://github.com/barrymcgee/vanilla-bug
2. Run `npm i`
3. Run `gulp build`
4. See error:

```
Error in plugin "sass"
Message:
    node_modules/vanilla-framework/scss/_patterns_icons.scss
Error: "%icon" failed to @extend "%vf-hide-text".
       The selector "%vf-hide-text" was not found.
       Use "@extend %vf-hide-text !optional" if the extend should be able to fail.
        on line 48 of node_modules/vanilla-framework/scss/_patterns_icons.scss
>>   @extend %vf-hide-text;

   ----------^
```
5. Run `npm i vanilla-framework@1.7.0`
6. Run `gulp build`
7. All is good, expected behavior.

```
 ~/projects/vanilla-test   master ● ?  gulp build                                                          
[19:22:45] Using gulpfile ~/projects/vanilla-test/gulpfile.js
[19:22:45] Starting 'build'...
[19:22:45] Finished 'build' after 112 ms

```

**Expected behavior**

Running `gulp build` should not throw errors.

**Comment by barrymcgee** [comment]
Update: switching the import from;

`@import 'vanilla-framework/scss/vanilla';`

...to...

`@import 'vanilla-framework/scss/build';`

..will fix the compilation error but it will then import that whole framework instead of allowing cherry-picking.

Just to note also: we currently recommend on the front page of https://docs.vanillaframework.io/en/ to import the former.

**Comment by lyubomir-popov** [comment]
@barrymcgee what version of gulp and node sass do you have globally installed?

**Comment by Caleb-Ellis** [comment]
The problem is occurring because importing `node_modules/vanilla-framework/scss/vanilla` is only doing half the job. The mixins aren't getting included in the sass build step, so you need `@include vanilla` to include all of Vanilla (as per the docs homepage), which `vanilla-framework/scss/build` does automatically. In your QA steps with only the import, if you build the css at Vanilla 1.7.0 nothing actually gets built. If you want to include only the components you need, you can import vanillla, then @include the mixins you need (see https://docs.vanillaframework.io/en/customising-vanilla#importing-individual-components).

**Comment by barrymcgee** [comment]
@Caleb-Ellis Thanks Caleb - you were certainly pointing in the right direction, adding;

```
@include vf-base;
```

...fixed all things! 💥
