### ISSUE TITLE
Follow DocBook admonitions for our Notifications?

### ISSUE THREAD

**Issue by nottrobin** [vanilla-framework/vanilla-framework#868]
During the docs sprint, @evilnick suggested that we follow a specific scheme for which [notification levels we provide](https://docs.vanillaframework.io/patterns/notification/), and that the [DocBook scheme](http://newbiedoc.sourceforge.net/tutorials/docbook-guide/admon-docbook-guide.html.en) would be a good candidate.

Currently we provide:

- Neutral (grey)
- Warning (yellow)
- Negative (red)
- Positive (green)

The DocBook "admonition" elements are instead:

- Note
- Caution
- Warning
- Tip
- Important

**Comment by anthonydillon** [comment]
Interestingly the first four line up quite nicely.
- Neutral -> Note
- Warning -> Caution
- Negative -> Warning
- Positive -> Tip

The only one not covered is important. Could important be one of the four
colours? We use a shade of blue in Juju for information. Maybe that could
be reused for important?

My 2 cents,
Ant.

On Thu, 16 Feb 2017, 08:17 Robin Winslow, <notifications@github.com> wrote:

During the docs sprint, @evilnick <https://github.com/evilnick> suggested
that we follow a specific scheme for which notification levels we provide
<https://docs.vanillaframework.io/patterns/notification/>, and that the DocBook
scheme
<http://newbiedoc.sourceforge.net/tutorials/docbook-guide/admon-docbook-guide.html.en>
would be a good candidate.

Currently we provide:

   - Neutral (grey)
   - Warning (yellow)
   - Negative (red)
   - Positive (green)

The DocBook "admonition" elements are instead:

   - Note
   - Caution
   - Warning
   - Tip
   - Important

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vanilla-framework/vanilla-framework/issues/868>, or mute
the thread

**Comment by barrymcgee** [comment]
We have decided this is not a valid proposal. Closing.

**Comment by matthewhelmke** [comment]
Info, tip, note, caution, and warning are extremely common in technical documentation. I would like to politely request that this please be reopened.

Note and caution are sometimes combined, as in this [Atlassian](https://confluence.atlassian.com/doc/info-tip-note-and-warning-macros-51872369.html) example. So does [MIT}(https://kb.mit.edu/confluence/pages/viewpage.action?pageId=150143125). So, I get where this may come from.

The cool thing about the DocBook scheme that @nottrobin mentions is that it conforms to the expected standard, including the automated use of [ISO 3864-1:2011](https://www.iso.org/standard/51021.html), which are described in a simpler fashion on [Wikipedia](https://en.wikipedia.org/wiki/Precautionary_statement), although that article is more US-centric focusing on the American [ANSI Z535 Safety Alerting Standards](http://www.nema.org/standards/z535/pages/default.aspx) standard, which is nearly identical to the ISO one.

**Comment by pmahnke** [comment]
@matthewhelmke don't worry, we are going to implement admonitions  in the docs theme and then if we see a need, propose it up to core Vanilla

**Comment by matthewhelmke** [comment]
Thank you!

**Comment by pmatulis** [comment]
I don't know if this is the right place but currently the admonishment for the MAAS docs does nothing but embolden the first word (and colon). It's a bit pointless. I would like **very much** to have some pale colour background (other than gray) for each type of admonishment. Including an appropriate small icon would be great too.
