### ISSUE TITLE
Further amends to Headings vertical rhythm

### ISSUE THREAD

**Issue by barrymcgee** [vanilla-framework/vanilla-framework#960]
As proposed by @spencerbygraves:

Adding these for different screen sizes.

**Large:**

- h1 = 48px
- h2 = 36px
- h3 = 28px
- h4 = 24px
- h5 = 20px
- h6 = 16px regular
- p = 16px

![afa143fe-0975-11e7-8a8a-903336df61c1](https://cloud.githubusercontent.com/assets/505570/23954730/f769d970-098f-11e7-86dc-a8cf8ea1db0e.png)

**Medium and small**

h1 = 32px
h2 = 28px
h3 = 24px
h4 = 22px
h5 = 18px
h6 = 16px regular
p = 16px

![f4d71cf0-0975-11e7-97d8-03fad151e65d](https://cloud.githubusercontent.com/assets/505570/23954749/03287b0e-0990-11e7-91c3-d254b6474497.png)

**Comment by barrymcgee** [comment]
@spencerbygraves Are these values, through each breakpoint, relative to each other? By that I mean, do they uniformly drop size by a consistent unit?

We use `rem` units throughout the framework and it would great to see these specs labelled with rems rather than pixels so the relationship between them is clearer. 

Currently, the base rem unit only has two variants, 15px at resolutions less than the medium breakpoint (768px) increasing to 16px above 768px. 

To reflect this, there should only be two variants of heading spec or we need to add another variant to the base rem - perhaps 14px/15px/16px.

**Comment by spencerbygraves** [comment]
@barrymcgee I did the sizing based on readability across a range of screen sizes, rather than using a set percentage drop each time.

It would be good to add the extra breakpoint so we're covering a better range of sizes.

**Comment by yaili** [comment]
The purpose of this demo is to test @spencerbygraves's new spec, so it would be good to add all the suggested breakpoints. In terms of specs, we create the design specs using pixels as that is the computed value that we want to achieve regardless of implementation. Hope this makes sense. We can discuss more tomorrow. Thank you.

**Comment by anthonydillon** [comment]
@barrymcgee to continue to develop the demo using the proposed values. Once this demo is ready, design will test the spacing across devices. Development will review the code and develop a good implementation.

Going forward, we will try and use rems in design specs.

**Comment by barrymcgee** [comment]
@spencerbygraves @yaili I've been playing experimenting with type scales and you can see how we can simplify and reduce the complexity by using a scale such as:

http://type-scale.com/?size=16&scale=1.250&text=Ubuntu%20Headings&webfont=Ubuntu&font-family=%27Ubuntu%27%2C%20serif&font-weight=300&font-family-headers=&font-weight-headers=inherit&background-color=white&font-color=%23333

We would switch `em` to `rem` here and you can see by changing the base size value on the top right to 14/15/16 to see how we could alter the sizing through the breakpoints.

**Comment by yaili** [comment]
@barrymcgee thanks for that. 

We had a quick catch up this morning (@kwm14 @spencerbygraves and me) to review the specs and your demo. Here's what we think we should do next to simplify things a little:

- Having only 2 breakpoints for the demo - large and medium sizes. We noticed that gov.uk do this, and our new specs are very similar between medium and small anyway (only h1 and h2 are different) so we think we probably don't need an extra step
- Base font size should always be 16px, as is in the new spec - the demo is still using 14-15-16px across breakpoints so we can't test the new spec yet. Can you make sure everything is included?
- Design spec to be in pixels, built in rems - other pattern libraries seem to specify type in pixels too
  - http://www.bbc.co.uk/gel/guidelines/typography
  - http://govuk-elements.herokuapp.com/typography/ (pixels in code!)
  - https://lightningdesignsystem.com/components/utilities/text/ (table at the bottom)
  - http://rizzo.lonelyplanet.com/styleguide/design-elements/typography (interesting numbers, thought because of rounding up rems, but no…)
- Explorations on the font sizes should try as much as possible to follow a relative scale - @spencerbygraves started with a relative scale when he first defined this new spec (like the one you sent), and added tweaks for better legibility

Hope this makes sense, any questions let me or @spencerbygraves know. Thanks!

**Comment by barrymcgee** [comment]
- We currently have only those two breakpoints, resulting in 3 variants. Which variant should be removed, small or medium?

- If we remove the base font size change from 14px to 15px that will affect multiple other patterns that have small/large variants based on the change, has that been taken into consideration?

- The links above, point to user facing docs - not specs passed between their designers/devs. And as an aside, even if they did, maybe we can lead the way with improved practice if it works out? As this was agreed in the Working Group after discussion with devs and designers, I'd like to see this at last trialled for a couple of weeks, what's to lose?

**Comment by anthonydillon** [comment]
We do have three breakpoints but we only change the base font size once. Small = 15px, medium = 16px and large = 16px. This is what is specced and desired. 

So with that in mind, let's build out what Spenser designed and see where we are from there.

Design have decided they would like to remain designing in pixels which we should respect and continue to convert for our needs.

**Comment by spencerbygraves** [comment]
@barrymcgee Thanks for updating the demo. I've had a look and I think there may have been a small confusion between what Lil and Ant said above.

It's looking good, but we decided to try only using the specs for large and medium sizes (see Lil's comment), the only difference between medium and small being h1 and h2. We also wanted to keep 16px as a base size throughout.

So, I think we're close. If we can try large and medium sizes as above, both with 16px base that would be great. Then, we may need to tweak the medium size h1/2 to work across both breakpoints.

if this works I guess we can just call them large and small.

Hopefully that makes sense, Thanks again.

**Comment by barrymcgee** [comment]
@spencerbygraves Now removed the small breakpoint and made sure all font-sizes are correct: http://barrymcgee.dreamhosters.com/vanilla-framework/examples/base/typo-scale/

**Comment by spencerbygraves** [comment]
@barrymcgee Thanks for the update, I think it's looking good. I'd like to check that @yaili is happy with the h1 and h2 sizes on small screen before we sign this off. I believe she's back from holiday on Monday.

One thing, h6 should be regular font weight to distinguish it from the body copy

**Comment by yaili** [comment]
Notes re: sizes in demo:
- h1 margin bottom should be 24px (large screen)
- h6 font weight should be 400 (regular)
- paragraph margin bottom should be 28px (medium screen)
- space between two paragraphs should be 24px (medium and large screen)
- block quote top and bottom margin should be 28px (medium screen)
- block quote top and bottom margin should be 32px (large screen)
- code block (pre) top and bottom margin - 28px (medium screen)
- code block (pre) top and bottom margin - 32px (large screen)
- images in specs have top and bottom spacing but not in demo
- figure caption should be italicised
- ul, ol and dl have 36px top and bottom margin in spec (large screen)

I agree with spencer that the h1 and h2 look a bit large in medium/small screens. Let's make them 32px (h1) and 28px (h2) as it was in the original small sizes spec. 

Thanks!

**Comment by yaili** [comment]
Had another look at updated demo:
- the space _between_ 2 paragraphs is still not 24px, it's 28px in the demo (also, can we have an example of this in the demo, so we don't have to manually add something)
- figcaption still not italicised - I think in @spencerbygraves 's spec the idea is that if there is a caption after an image the spacing is not duplicated
- something odd is happening with nested lists - odd bullets and spacing between list items
- can you please add an example of blockquote with paragraph and cite to the demo?
- ul and ol don't have correct bottom margin yet
- h1 and h2 font size hasn't been changed in small screen
- code block (pre) bottom margin in small should be 28px (like top)

In terms of the actual typographic scale and spacing _values_, once the items mentioned above are fixed I think it will be fine. But I'm concerned about the way this has been specified in the CSS and how it will affect other patterns. For example, the headings have margin-top applied to them, which we know doesn't work when we put things inside boxes. Have we thought about how this will work? I think @richmccartney had some ideas on how this could be done so that each element could be placed inside anything and it wouldn't break the parent's inner spacing, if that makes sense. What's the plan, @barrymcgee @anthonydillon ?

**Comment by richmccartney** [comment]
Hi @yaili I've made a SassMeister which creates a typographic spacing close to @spencerbygraves it's not the exact scale but the demo here shows how it would keep a basic spacing between elements and specifies explicit styles to those effected further.

[Demo](http://www.sassmeister.com/gist/109bbcfc4e2c08fd382e3833a6467cd6)

As you can read the only elements that get special treatment are h1's as the row facilitates any block spacing at the top. Then if there are any specific spacing for example for spacing between a ```label``` and ```input``` the following code would be written:

```
label {
  
  + * {
    margin-top: $global-spacing-unit-sm;
  }
}
```

I would suggest using this as a basis, rip out any margin spacing and build on top of it to keep the vertical scale. We can talk about it further if needed.

**Comment by barrymcgee** [comment]
@yaili Demo now updated again: http://barrymcgee.dreamhosters.com/vanilla-framework/examples/base/typo-scale/

Re: cascading to other patterns - I've been monitoring Percy throughout this and correcting any pattern that is adversely affected by these changes. You can view all the elements that will be affected by these changes here:

https://percy.io/vanilla-framework/vanilla-framework/builds/198958

Everything that is currently flagged is expected in my opinion.
