### ISSUE TITLE
Remove navigation margin

### ISSUE THREAD

**Issue by anthonydillon** [vanilla-framework/vanilla-framework#982]
Currently, the navigation pattern has `margin-bottom: 2rem`. This causes a white strip between the navigation and the first row.

![10544614](https://cloud.githubusercontent.com/assets/1413534/24459499/a054c3a2-1493-11e7-8a9e-b3dd0a31ace1.png)

**Comment by yaili** [comment]
Should we be moving away from having margins as part of patterns? Because that makes them less flexible to be used anywhere.

**Comment by anthonydillon** [comment]
Yes and maybe the reason to consider `strip--hero`.

**Comment by yaili** [comment]
You mean strip--hero would have something like margin-top -2rem? Sounds dirty…

**Comment by anthonydillon** [comment]
No. If navigation doesn't have margin bottom but we want that extra space
then strip--hero could have more padding at the top then a normal strip.

**Comment by barrymcgee** [comment]
But that assumes that every page will start with a hero strip, or even a strip. The margin bottom on the navigation was added because adding a simple `.row > .col-12 > p` after the nav without margin-bottom meant there was no space between the two -

<img width="667" alt="screen shot 2017-03-30 at 09 12 52" src="https://cloud.githubusercontent.com/assets/505570/24494189/518c7e4a-1529-11e7-8d46-e4674b4ff311.png">

Strips are a pattern, not a grid construct, people should not _have_ to use them.

**Comment by yaili** [comment]
What do you have to use? Rows? I don't think navigation should have any margin around it, it should be the rest of the content which defines whether any space is needed or not. There is a separate proposal for strips to have shallow or deep top/bottom padding. Should that be row instead? I'm confused.
